/* ALI: arithmetic & logical instructions             */  #include "ALI/ALI.h"
/* CTI: control transfer instructions                 */  #include "CTI/CTI.h"
/* DMI: data movement instructions                    */  #include "DMI/DMI.h"
/* SCTI: string and character translation instructions*/  #include "SCTI/SCTI.h"
/* SI: system instructions                            */  #include "SI/SI.h"
/* FCI: flag contril instruction                      */  #include "FCI/FCI.h"
/* misc: miscellaneous instructions                   */  #include "misc/misc.h"
